<?php
// $Id: xoops_version.php,v 1.3 2005/03/14 20:05:43 jsaucier Exp $
//  ------------------------------------------------------------------------ //
//                           Document Manager                                //
//            Copyright (c) 2004 Informatique Strategique IS                 //
//                  <http://www.infostrategique.com/>                        //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


// Global information
$modversion['name'] = _MI_FCABIX_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_FCABIX_DESC;
$modversion['author'] = "Director and PHP programing by Yoshi Sakai / Designer and Javascript programing by makinosuke";
$modversion['credits'] = "Copyright(c) Bluemoon inc. ( www.bluemooninc.biz )
Based module as DocManager V1.1 by Jeff Saucier ( www.infostrategique.com )
Icon design by Tango Desktop Project ( tango.freedesktop.org )
jQuery and plugins ( uplodify, flexigrid, treeview, ifixpng, ui, ifixpng )
";
$modversion['help'] = "docs/README";
$modversion['license'] = "GPL see gpl.txt";
$modversion['official'] = 0;
$modversion['image'] = "images/fcabix_slogo.gif";
$modversion['dirname'] = "fcabix";


// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";


// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "fcabix_folders";
$modversion['tables'][1] = "fcabix_files";
$modversion['tables'][2] = "fcabix_configs";
$modversion['tables'][3] = "fcabix_rights";



// Admin things

$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";



// Menu
$modversion['hasMain'] = 1;


// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "fcabix_search";


// Templates
$modversion['templates'][] = array('file'=>'fcabix_index.html'       ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_createfolder.html','description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_erasefolder.html' ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_modfolder.html'   ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_createfile.html'  ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_erasefile.html'   ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_modfile.html'     ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_attrfolder.html'  ,'description'=>'');
$modversion['templates'][] = array('file'=>'fcabix_insertinfo.html'  ,'description'=>'');

// Admin Preferences

$modversion['config'][] = array(
	'name'        => 'ext_filter',
	'title'       => '_MI_FCABIX_EXTFILTER',
	'description' => '',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => 'gif,jpeg,jpg,png,pdf,zip,doc,xls,ppt,csv'
);
$modversion['config'][] = array(
	'name'        => 'max_filesize',
	'title'       => '_MI_FCABIX_MAXFILESIZE',
	'description' => '',
	'formtype'    => 'textbox',
	'valuetype'   => 'int',
	'default'     => '1048576'
);
$modversion['config'][] = array(
	'name'        => 'max_filenum',
	'title'       => '_MI_FCABIX_UPLOAD_MAXNUM',
	'description' => '',
	'formtype'    => 'textbox',
	'valuetype'   => 'int',
	'default'     => '128'
);
$modversion['config'][] = array(
	'name'        => 'fcabixWidth',
	'title'       => '_MI_FCABIX_WIDTH',
	'description' => '',
	'formtype'    => 'textbox',
	'valuetype'   => 'int',
	'default'     => null
);
$modversion['config'][] = array(
	'name'        => 'treeViewUnique',
	'title'       => '_MI_FCABIX_TREEVIEWUNIQUE',
	'description' => '',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 0
);
$modversion['config'][] = array(
	'name'        => 'use_flash',
	'title'       => '_MI_FCABIX_USEFLASH',
	'description' => '',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 1
);

?>